# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Thread',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='topic_title',
            new_name='thread_title',
        ),
    ]
