# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_thread_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_in_thread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
