# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20160713_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_post', 'Can change the post'),)},
        ),
    ]
