# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20160714_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_post_instance', 'Can change the post'),)},
        ),
    ]
