# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20160715_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_thread',
            field=models.BooleanField(default=False),
        ),
    ]
