# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_post_is_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_in_thread',
        ),
    ]
