# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_post_number_in_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(default=''),
        ),
    ]
