# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.BigIntegerField(),
        ),
    ]
