# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20160730_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
