# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20160730_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
