# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_userkey_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_title',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
