# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20160731_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='full_text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
