# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20160810_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_title',
            field=models.CharField(max_length=70),
        ),
    ]
