# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20160810_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['precedence'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='raw_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='raw_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_title',
            field=models.CharField(max_length=70, verbose_name='title'),
        ),
    ]
