# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20160824_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 15, 9, 18, 218358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 15, 9, 18, 218358, tzinfo=utc)),
        ),
    ]
