# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20160828_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
