# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20160828_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thread',
            name='edit_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
